lang: zh-CN

# 网站基本信息
title: 个人网站
description: 为了积累我的个人知识，创立了这个网站。
url: "https://agemoonage.github.io" # GitHub Pages 的主地址
baseurl: "/site" # 仓库名为 site

# GitHub 用户名
github_username: agemoonage

# 构建设置
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# 可选：显示在页面底部的时间格式
timezone: Asia/Shanghai


